// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtGgsKmDLlOO3DeBtHemuL5Ou1jPt3T0',
    appId: '1:378259077893:web:26322801671f8b3b21956c',
    messagingSenderId: '378259077893',
    projectId: 'ecom-r2',
    authDomain: 'ecom-r2.firebaseapp.com',
    storageBucket: 'ecom-r2.appspot.com',
    measurementId: 'G-XSVWHSY39P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5opYN3wWxYgiTCTGulzBbJ-SNkUjF1UM',
    appId: '1:378259077893:android:1eb9abbe46a40d5221956c',
    messagingSenderId: '378259077893',
    projectId: 'ecom-r2',
    storageBucket: 'ecom-r2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvOAGMOk0amj6_wIV0w2_i3L0bQUQnm8',
    appId: '1:378259077893:ios:bb2d3e5cccec03a721956c',
    messagingSenderId: '378259077893',
    projectId: 'ecom-r2',
    storageBucket: 'ecom-r2.appspot.com',
    iosBundleId: 'com.example.rePr2Sakshi2453',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvOAGMOk0amj6_wIV0w2_i3L0bQUQnm8',
    appId: '1:378259077893:ios:b0a56917a06afb4621956c',
    messagingSenderId: '378259077893',
    projectId: 'ecom-r2',
    storageBucket: 'ecom-r2.appspot.com',
    iosBundleId: 'com.example.rePr2Sakshi2453.RunnerTests',
  );
}
